# Pandas 기초연습문제

In [2]:
import pandas as pd

## 1. 딕셔너리를 이용하여 아래와 같은 모양이 되도록 data frame을 생성하시오.

In [4]:
score={'학번':[201524213,201621223,201621233, 201611111, 201722222],
       '이름':['오지환','박용택','정성훈', '다니엘', '지민'],
       '학과':['경영정보','경영정보','경영정보','컴퓨터공학','컴퓨터공학'],
       'Quiz':[15,20,10,17,18],
       '중간고사':[20,20,15,18,16]}

df= pd.DataFrame(score)
df

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
2  201621233  정성훈   경영정보    10    15
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16

In [5]:
df['학번']

0    201524213
1    201621223
2    201621233
3    201611111
4    201722222
Name: 학번, dtype: int64

## 2. 위에서 생성한 데이터프레임으로부터 인덱싱을 이용하여 이름과 중간고사를 추출하시오.

In [7]:
df[['이름', '중간고사']] #이름, 중간고사 열만 추출

이름  중간고사
0  오지환    20
1  박용택    20
2  정성훈    15
3  다니엘    18
4   지민    16

## 3. reindex를 이용하여 2, 0, 4, 1, 3 순으로 순서를 변경하시오.

In [11]:
df = df.reindex([2, 0, 4, 1, 3]) #인덱스 순서를 변경해 추출
df

학번   이름     학과  Quiz  중간고사
2  201621233  정성훈   경영정보    10    15
0  201524213  오지환   경영정보    15    20
4  201722222   지민  컴퓨터공학    18    16
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

## 4. iloc과 loc을 각각 이용하여 박용택 학생의 record를 추출하시오. (iloc으로 한번, loc으로 한번 수행)


In [13]:
print(df.iloc[3])
print(df.loc[1])

학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object
학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object


## 5. iloc과 loc을 각각 이용하여 모든 학생의 이름과 중간고사 점수를 추출하시오. (iloc으로 한번, loc으로 한번 수행)

In [15]:
print(df.iloc[:, [1, 4]])
print(df.loc[:, ['이름', '중간고사']])

    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18
    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18


## 6. 중간고사 점수의 평균을 구하시오.

In [17]:
df['중간고사'].mean()

17.8

## 7. 중간고사 점수가 가장 낮은 학생의 index를 구하시오.

In [19]:
df['중간고사'].idxmin()

2

## 8. 퀴즈 점수가 가장 높은 학생의 학번을 구하시오.

In [22]:
df.loc[df['Quiz'].idxmax(), '학번']
#df.loc[df['Quiz'].idxmax()]['학번']

201621223

## 9. 위 데이터프레임의 각 열에 대해서 개수, 평균, 표준편차, 최소최대값 등의 다양한 통계량을 출력하시오.

In [24]:
df.describe() # df의 통계량

학번       Quiz       중간고사
count  5.000000e+00   5.000000   5.000000
mean   2.016200e+08  16.000000  17.800000
std    7.018995e+04   3.807887   2.280351
min    2.015242e+08  10.000000  15.000000
25%    2.016111e+08  15.000000  16.000000
50%    2.016212e+08  17.000000  18.000000
75%    2.016212e+08  18.000000  20.000000
max    2.017222e+08  20.000000  20.000000

## 10. 위 데이터프레임을 중간고사 점수에 따라 내림차순으로 정렬하시오.

In [26]:
df.sort_values('중간고사', ascending=False)

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16
2  201621233  정성훈   경영정보    10    15

## 11. 학생 중에서 퀴즈 점수가 평균 이상인 학생들의 이름을 출력하시오.

In [28]:
quiz_mean = df['Quiz'].mean()
df[df['Quiz'] > quiz_mean]['이름']

4     지민
1    박용택
3    다니엘
Name: 이름, dtype: object

## 12. 학생 중에서 퀴즈와 중간고사 점수 모두 평균 이상인 학생들의 record를 출력하시오.

In [30]:
quiz_mean = df['Quiz'].mean()
mid_mean = df['중간고사'].mean()
df[(df['Quiz'] > quiz_mean) & (df['중간고사'] > mid_mean)]

학번   이름     학과  Quiz  중간고사
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

## 13. value_counts를 이용하여 학과 별로 학생의 수를 구하시오.

In [32]:
df['학과'].value_counts()

경영정보     3
컴퓨터공학    2
Name: 학과, dtype: int64

## 14. groupby를 이용하여 학과 별로 중간고사의 평균을 구하시오.

In [34]:
df.groupby('학과')['중간고사'].mean()

학과
경영정보     18.333333
컴퓨터공학    17.000000
Name: 중간고사, dtype: float64

In [35]:
df.mean()

학번      201620000.4
Quiz           16.0
중간고사           17.8
dtype: float64

In [37]:
list(df.groupby('학과')) #학과 기준으로 groupby

[('경영정보',           학번   이름    학과  Quiz  중간고사
  2  201621233  정성훈  경영정보    10    15
  0  201524213  오지환  경영정보    15    20
  1  201621223  박용택  경영정보    20    20),
 ('컴퓨터공학',           학번   이름     학과  Quiz  중간고사
  4  201722222   지민  컴퓨터공학    18    16
  3  201611111  다니엘  컴퓨터공학    17    18)]

-----------------------------------------------
# Numpy 기초연습문제

In [39]:
import numpy as np

## 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [41]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [43]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [44]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

## 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [46]:
a[1, 2] # 2번째 행에서 3번째 열값 추출

7.0

## 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [48]:
a.shape

(3, 4)

In [49]:
a[[1], :]

array([[5., 6., 7., 8.]])

## 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

In [51]:
a[:,[0, 2]]

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

## 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

In [53]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [54]:
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

## 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [56]:
b = np.random.random((3, 4)) #3행 4열인 0~1사이 값 랜덤 생성
b

array([[0.44736089, 0.96360774, 0.31328195, 0.24450837],
       [0.75511356, 0.46260271, 0.68622208, 0.22934387],
       [0.03032997, 0.38478133, 0.2430969 , 0.04498148]])

## 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [58]:
c = a * b
c

array([[0.44736089, 1.92721549, 0.93984585, 0.97803347],
       [3.77556778, 2.77561629, 4.80355457, 1.834751  ],
       [0.27296977, 3.84781327, 2.67406587, 0.53977775]])

## 9. b의 전치행렬을 구하여 d에 저장하시오.

In [60]:
d = b.T
d

array([[0.44736089, 0.75511356, 0.03032997],
       [0.96360774, 0.46260271, 0.38478133],
       [0.31328195, 0.68622208, 0.2430969 ],
       [0.24450837, 0.22934387, 0.04498148]])

In [61]:
d.shape

(4, 3)

## 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [63]:
print(a.shape, d.shape)

(3, 4) (4, 3)


## 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [66]:
e = a.dot(d) #행렬곱
e

array([[ 4.29245571,  4.65636073,  1.70910924],
       [12.16749153, 13.18948963,  4.52186796],
       [20.04252736, 21.72261853,  7.33462667]])

## 12. e에 대하여 각 열의 합을 계산하시오.

In [68]:
np.sum(e, axis=1)

array([10.65792567, 29.87884912, 49.09977257])